[package]
authors = ["Matteo Paonessa <matteo.paonessa@gmail.com>"]
categories = ["multimedia::images"]
description = "A lossy/lossless image compression library."
edition = "2021"
exclude = [
  "tests/*",
  ".github/*",
  ".idea/*",
]
homepage = "https://github.com/Lymphatus/libcaesium"
keywords = [
  "compression",
  "jpeg",
  "png",
  "gif",
  "webp",
]
license = "Apache-2.0"
name = "libcaesium"
readme = "README.md"
repository = "https://github.com/Lymphatus/libcaesium"
rust-version = "1.90"
version = "0.21.2"

[features]
default = ["jpg", "png", "webp", "gif", "tiff", "parallel"]
gif = ["dep:gifski", "dep:gif", "dep:gif-dispose", "dep:rayon", "image/gif"]
jpg = ["dep:mozjpeg-sys", "image/jpeg"]
parallel = ["oxipng?/parallel", "imagequant?/threads", "dssim/threads"]
png = ["dep:oxipng", "dep:lodepng", "dep:imagequant", "image/png"]
tiff = ["dep:tiff", "image/tiff"]
webp = ["dep:webp", "image/webp"]

[dependencies]
bytes = "1.7"
gif = {version = "0.14", optional = true}
gif-dispose = {version = "6.0", optional = true}
gifski = {version = "1.34", optional = true}
image = {version = "0.25", default-features = false}
imagequant = {version = "4.3", optional = true, default-features = false}
img-parts = "0.4.0"
imgref = "1.12"
infer = "0.22"
kamadak-exif = "0.6"
libc = "0.2"
lodepng = {version = "3.10", optional = true}
mozjpeg-sys = {version = "2.1", optional = true}
oxipng = {version = "10.2", default-features = false, features = ["zopfli"], optional = true}
rayon = {version = "1.12", optional = true}
tiff = {version = "0.11", optional = true}
webp = {version = "0.3.1", optional = true}

[target.wasm32-unknown-emscripten.dependencies]
libwebp-sys = "=0.9.5"

[dev-dependencies]
dssim = {version = "3.3", default-features = false, features = ["no-macos-vimage"]}
rayon = "1.12"

[lib]
bench = false
crate-type = ["lib", "cdylib"]
doc = false
doctest = false
name = "caesium"
path = "src/lib.rs"
test = true
